use sqlx::SqlitePool;

use crate::db::{items, repos};
use crate::scanner::RepoConfig;

pub async fn regenerate(pool: &SqlitePool, repo_id: &str) -> Result<(), anyhow::Error> {
    let repo = repos::get(pool, repo_id).await?;
    let all_items = items::list_by_repo(pool, repo_id, None).await?;
    let repo_path = std::path::Path::new(&repo.path);
    let roadmap_path = repo_path.join("ROADMAP.md");

    let now = chrono::Local::now().format("%Y-%m-%d").to_string();

    let count = |s: &str| all_items.iter().filter(|i| i.status == s).count();
    let in_progress = count("in_progress");
    let todo        = count("todo");
    let backlog     = count("backlog");
    let done        = count("done");
    let canceled    = count("canceled");
    let total       = all_items.len();

    let mut md = format!(
        "---\ntitle: Roadmap — {name}\ntype: roadmap\ngenerated: {now}\n---\n\n\
# Roadmap — {name}\n\n\
> Index auto-gerado por roadmap-manager em {now}. \
Caminhos de arquivo são relativos à raiz do repositório.\n\n\
| Status | Count |\n\
|---|---|\n\
| 🔄 In Progress | {in_progress} |\n\
| 📋 Todo | {todo} |\n\
| ⬜ Backlog | {backlog} |\n\
| ✅ Done | {done} |\n\
| ❌ Canceled | {canceled} |\n\
| **Total** | **{total}** |\n\n",
        name = repo.name,
        now = now,
    );

    let status_groups = [
        ("in_progress", "🔄 In Progress"),
        ("todo",        "📋 Todo"),
        ("backlog",     "⬜ Backlog"),
        ("done",        "✅ Done"),
        ("canceled",    "❌ Canceled"),
        ("duplicate",   "🔗 Duplicate"),
    ];

    for (status_key, label) in &status_groups {
        let group: Vec<_> = all_items.iter().filter(|i| i.status == *status_key).collect();
        if group.is_empty() {
            continue;
        }

        md.push_str(&format!("## {} ({})\n\n", label, group.len()));
        md.push_str("| ID | Título | Arquivo | Prioridade | Labels | Depende de |\n");
        md.push_str("|---|---|---|---|---|---|\n");

        for item in &group {
            let rel_path = std::path::Path::new(&item.file_path)
                .strip_prefix(repo_path)
                .unwrap_or(std::path::Path::new(&item.file_path))
                .to_string_lossy()
                .to_string();

            let priority = item.priority.as_deref().unwrap_or("—");

            let labels: Vec<String> = serde_json::from_str(&item.labels).unwrap_or_default();
            let labels_str = if labels.is_empty() {
                "—".to_string()
            } else {
                labels.join(", ")
            };

            let deps: Vec<String> = serde_json::from_str(&item.depends_on).unwrap_or_default();
            let deps_str = if deps.is_empty() {
                "—".to_string()
            } else {
                deps.join(", ")
            };

            let safe_title = item.title.replace('|', "\\|");

            md.push_str(&format!(
                "| {} | {} | `{}` | {} | {} | {} |\n",
                item.external_id, safe_title, rel_path, priority, labels_str, deps_str
            ));
        }
        md.push('\n');
    }

    std::fs::write(&roadmap_path, &md)?;

    let _ = regenerate_indexes(pool, repo_id).await;

    Ok(())
}

pub async fn regenerate_indexes(pool: &SqlitePool, repo_id: &str) -> Result<u32, anyhow::Error> {
    let repo = repos::get(pool, repo_id).await?;
    let config: RepoConfig = serde_json::from_str(&repo.config)?;
    let all_items = items::list_by_repo(pool, repo_id, None).await?;
    let repo_path = std::path::Path::new(&repo.path);

    let mut updated = 0u32;

    for (type_name, template) in &config.templates {
        let generate = template
            .defaults
            .get("generateIndex")
            .and_then(|v| v.as_bool())
            .unwrap_or(true);

        if !generate {
            continue;
        }

        let dirs = crate::scanner::discover_template_dirs(repo_path, &template.dir);
        for dir in &dirs {
            let rel_dir = dir
                .strip_prefix(repo_path)
                .unwrap_or(dir)
                .to_string_lossy()
                .to_string();

            let dir_items: Vec<_> = all_items
                .iter()
                .filter(|i| i.item_type == *type_name && i.file_path.starts_with(&rel_dir))
                .collect();

            if dir_items.is_empty() {
                continue;
            }

            let index_path = dir.join("INDEX.md");
            let now = chrono::Local::now().format("%Y-%m-%d").to_string();

            let mut md = format!(
                "# {} — Index\n\n> Auto-generated by roadmap-manager on {}.\n\n",
                type_name, now
            );

            let status_groups = [
                ("in_progress", "🔄 In Progress"),
                ("todo", "📋 Todo"),
                ("backlog", "⬜ Backlog"),
            ];

            for (status_key, label) in &status_groups {
                let group: Vec<_> = dir_items
                    .iter()
                    .filter(|i| i.status == *status_key && !i.file_path.contains("_archive/"))
                    .collect();
                if group.is_empty() {
                    continue;
                }
                md.push_str(&format!("## {}\n\n", label));
                for item in &group {
                    let priority = item.priority.as_deref().unwrap_or("—");
                    md.push_str(&format!(
                        "- [{}] {} — {} — {}\n",
                        item.external_id, item.title, item.status, priority
                    ));
                }
                md.push('\n');
            }

            let shipped: Vec<_> = dir_items
                .iter()
                .filter(|i| {
                    matches!(i.status.as_str(), "done" | "canceled" | "duplicate")
                        || i.file_path.contains("_archive/")
                })
                .collect();
            if !shipped.is_empty() {
                md.push_str("## Shipped\n\n");
                for item in &shipped {
                    let priority = item.priority.as_deref().unwrap_or("—");
                    md.push_str(&format!(
                        "- [{}] {} — {} — {}\n",
                        item.external_id, item.title, item.status, priority
                    ));
                }
                md.push('\n');
            }

            let existing = std::fs::read_to_string(&index_path).unwrap_or_default();
            let new_hash = crate::parser::hash(&md);
            let old_hash = crate::parser::hash(&existing);

            if new_hash != old_hash {
                std::fs::write(&index_path, &md)?;
                updated += 1;
            }
        }
    }

    Ok(updated)
}
